version: '3.1.1'
services:
  backend:
    container_name: EnocaBackendProject
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - PostgreSQL
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://PostgreSQL:5432/enocaprojectDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

  PostgreSQL:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=enocaprojectDb
